### ISSUE TITLE
Add asynchronous streams

### ISSUE THREAD

**Issue by ricardoalcaraz** [PereViader/Scrolller.Net#3]
Cool little library. Never knew about scrolller now im using it to  download images off Reddit. I noticed your library doesn't allow the data to be paged. I also noticed the API itself provides an iterator for easy paging 😅. 

Adding an asynchronous stream to the api will allow us to download as much of the dataset as we want. If you're open to pull requests I can submit some changes that will add the feature.

**Comment by PereViader** [comment]
Totally open to PRs.
My usecase is really simple just get a bunch of assets and show them one by one.
Happy to add asynchronous stream if you can implement it 👍

**Comment by ricardoalcaraz** [comment]
Cool added a PR for this feature: https://github.com/PereViader/Scrolller.Net/pull/5
